### PR TITLE
Create strings.xml for Turkish

### PR DESCRIPTION
**Pull request by anilmavis**

### CODE REVIEW

**Comment by sunilpaulmathew** [comment]
@anilmavis 
Thanks a lot, and accepting the PR now.

**Comment by sunilpaulmathew** [comment]
@anilmavis 
By the way, just to confirm is it turkish for Turkey (not Cyprus)? If so, it will be probably values-tr-rTR (please clarify, then, I'll move it to the respective place).

**Comment by anilmavis** [comment]
> 
> 
> @anilmavis
> By the way, just to confirm is it turkish for Turkey (not Cyprus)? If so, it will be probably values-tr-rTR (please clarify, then, I'll move it to the respective place).

Hi, it is for Turkey. By the way, the application is very helpful. Thanks a lot! :)

**Comment by sunilpaulmathew** [comment]
> > @anilmavis
> > By the way, just to confirm is it turkish for Turkey (not Cyprus)? If so, it will be probably values-tr-rTR (please clarify, then, I'll move it to the respective place).
> 
> Hi, it is for Turkey. By the way, the application is very helpful. Thanks a lot! :)

Nice, and thanks for the nice words.
Maybe you can test a new APK ([attached here](https://www.dropbox.com/s/bh55fme9avutlwt/com.sunilpaulmathew.translator.apk?dl=0)). Don't be surprised about the new settings page (I'm updating it now)

**Comment by anilmavis** [comment]
> 
> 
> > > @anilmavis
> > > By the way, just to confirm is it turkish for Turkey (not Cyprus)? If so, it will be probably values-tr-rTR (please clarify, then, I'll move it to the respective place).
> > 
> > 
> > Hi, it is for Turkey. By the way, the application is very helpful. Thanks a lot! :)
> 
> Nice, and thanks for the nice words.
> Maybe you can test a new APK ([attached here](https://www.dropbox.com/s/bh55fme9avutlwt/com.sunilpaulmathew.translator.apk?dl=0)). Don't be surprised about the new settings page (I'm updating it now)

I tested the new APK. There are small translation problems. I will update them as soon as possible.

**Comment by sunilpaulmathew** [comment]
> > > > @anilmavis
> > > > By the way, just to confirm is it turkish for Turkey (not Cyprus)? If so, it will be probably values-tr-rTR (please clarify, then, I'll move it to the respective place).
> > > 
> > > 
> > > Hi, it is for Turkey. By the way, the application is very helpful. Thanks a lot! :)
> > 
> > 
> > Nice, and thanks for the nice words.
> > Maybe you can test a new APK ([attached here](https://www.dropbox.com/s/bh55fme9avutlwt/com.sunilpaulmathew.translator.apk?dl=0)). Don't be surprised about the new settings page (I'm updating it now)
> 
> I tested the new APK. There are small translation problems. I will update them as soon as possible.

In that case, please have a look at the latest strings. Few more are added for the settings page. & Take your time.

**Pull request merged**
