### PR TITLE
Create Chinese Strings.xml

### PR DESCRIPTION
**Pull request by sr093906**

### CODE REVIEW

**Comment by sr093906** [comment]
There could be a typo in line 10. Should be 'Kernel Auditor'

**Comment by sunilpaulmathew** [comment]
> Kernel Auditor

Thanks a lot for your efforts. According to the author of that app, the Latin word "Adiutor" means Helper (please see the source code [here](https://github.com/Grarak/KernelAdiutor#kerneladiutor)).

By the way, is it Chinese traditional or the simplified version? In that case, we have to move it to values-zh-rCN (simplified) or values-zh-rTW (traditional). Please let me know, then I'll take care of it. Accepting the request now.

**Comment by sr093906** [comment]
@sunilpaulmathew Wow, its is a Latin word. Please move to dir 'values-zh-rCN'.

**Comment by sunilpaulmathew** [comment]
> @sunilpaulmathew Wow, it is a Latin word. Please move to dir 'values-zh-rCN'.

Will be done, and post a test build for you later today. Have a nice day...

**Comment by sunilpaulmathew** [comment]
> @sunilpaulmathew Wow, it is a Latin word. Please move to dir 'values-zh-rCN'.

Can you test [this](https://www.dropbox.com/s/bh55fme9avutlwt/com.sunilpaulmathew.translator.apk?dl=0) when you have time?

**Comment by sr093906** [comment]
Hi,

Thanks. I tested it on my phone. It looks good.

sp <notifications@github.com> 于 2021年1月9日周六 00:50写道：

**Pull request merged**
