### PR TITLE
Update fr translation

### PR DESCRIPTION
**Pull request by roptat**
Automatically submitted using Offlate. Report translation issues to the submitter, and Offlate issues to @roptat, thanks!

### CODE REVIEW

**Comment by roptat** [comment]
Hm, one commit per file was probably a bad idea, feel free to squash before merging :)

As you can see, I have my own tool that lets me translate :D. It works in a similar fashion to stringlate, but more generic (more types of files are supported), and works on PC, not android.

**Comment by roptat** [comment]
ah, it's missing something, I had at least one more string translated, let me fix that...

**Comment by roptat** [comment]
Sorry for spamming you with notifications, it should be good now.

**Comment by sunilpaulmathew** [comment]
@roptat 
Manually picked it here 9c46e9458a03027807dbbca5b6f9d83ad302d87e
Also, I haven't picked change-logs. I think it won't be picked by the F-Droid server unless it is there with the release tag.

**Pull request closed without merging**
