### PR TITLE
Update Chinese Strings

### PR DESCRIPTION
**Pull request by sr093906**

### CODE REVIEW

**Comment by sunilpaulmathew** [comment]
Manually picked it, with full authorship to you, [here](https://github.com/sunilpaulmathew/Translator/commit/5aa9dbdfc9bff834880762979f763a860a8de4bd).

**Comment by sr093906** [comment]
@sunilpaulmathew Thanks. Could you merge it into master branch?

**Comment by sunilpaulmathew** [comment]
> ou merge it into

Its already merged. Only need little more time to release a new version.

**Comment by sr093906** [comment]
Thanks. Closing the pull request.

**Pull request closed without merging**
